name: yuyan_app

description: 雨燕，一款第三方语雀移动客户端

version: 1.1.1+1.1.1

environment:
  sdk: ">=2.10.0 <3.0.0"

publish_to: none

dependency_overrides:
  crypto: 3.0.0

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  ## flutter图标相关
  cupertino_icons: ^1.0.0
  font_awesome_flutter: ^8.7.0

  # 富文本编辑器, Bug多多
  zefyr:
    git:
      url: git@github.com:dreamer2q/zefyr.git
      ref: nullsafety
      path: packages/zefyr

  notus: 1.0.0-dev.4.0
  #  notus:
  #    git:
  #      url: git@github.com:dreamer2q/zefyr.git
  #      ref: nullsafety
  #      path: packages/notus

  # 底部导航栏
  curved_navigation_bar: ^0.3.1

  # HTML渲染部分，主要用于渲染语雀文档
  ## 文档瞄点
  scroll_to_index: 1.0.6
  ## html渲染
  flutter_html: # ^1.3.0
    git:
      ref: 47e3931596dc4bb1d5f6e6a38d829e91e54d9abb
      url: https://github.com/vrtdev/flutter_html.git
  ## 代码高亮支持
  flutter_highlight: 0.6.0
  ## clipboard复制代码
  clipboard: 0.1.2+8
  ## 组件显示，支持缩放
  photo_view: 0.10.3
  ## 图片缓存
  cached_network_image: ^2.0.0
  ## 图片查看，编辑
  extended_image: 3.0.0
  ## 视频播放
  chewie: ^1.0.0
  ## svg渲染
  flutter_svg: ^0.21.0-nullsafety.0

  # Webview相关
  flutter_webview_plugin:
    git: https://github.com/aboutmydreams/flutter_webview_plugin.git
  flutter_inappwebview: 4.0.0+4

  ## 多返回值
  tuple: 2.0.0

  # goodlook guide 液体
  liquid_swipe: ^1.5.0
  flutter_swiper: 1.1.6

  # 网络请求
  dio: 4.0.0-beta7
  pretty_json: 1.1.0

  # 弱提示
  # fluttertoast: ^3.1.3
  bot_toast: 3.0.5

  # launcher
  url_launcher: ^5.0.0

  # 有序列表
  romanice: 1.0.0+1

  # 下拉刷新
  pull_to_refresh: 1.6.4

  # 写入文件
  path_provider: ^2.0.1

  # 状态管理
  scoped_model: ^1.0.1
  get: 4.0.0-nullsafety.2

  # 数据分析
  #  firebase_core: ^0.5.3 # This dependency was added during initial configuration.
  #  firebase_analytics: ^6.3.0 # add dependency for Google Analytics for Firebase

  # 缓存
  shared_preferences: ^2.0.5
  get_storage: 2.0.1

  # 分享
  share_extend: ^1.1.9
  # 权限
  permission_handler: ^5.0.0+hotfix.8
  # flare动画
  flare_flutter: ^2.0.6

  # 裁剪 我的页面顶部背景
  flutter_custom_clippers: ^1.1.0
  # 列表动画
  flutter_staggered_animations: 1.0.0
  # 话题标签颜色
  smart_color: ^0.2.2

  # 消息红点
  badges: ^1.1.0

  # 评论 下滑出的抽屉
  sliding_up_panel: ^1.0.1

  # 更新apk https://github.com/xuexiangjys/XUpdate
  flutter_xupdate: ^1.0.2

  # 获取版本号
  package_info: ^0.4.3+2

  # 滑动tab
  shifting_tabbar: ^0.3.1

  # 图片选择器
  image_picker: ^0.7.2

  # lake to markdown
  html2md: ^1.0.1

  # markdown 渲染器
  flutter_markdown: ^0.5.2

  ## 字符串格式
  recase: 3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/js/
    - assets/flares/
    - assets/images/
    - assets/images/guide/
    - assets/images/explore/
    - assets/images/dashboard/
    - assets/images/news/
    - assets/images/my_page/
    - assets/images/card/

  fonts:
    - family: Silom
      fonts:
        - asset: assets/fonts/Silom.ttf
    - family: sans_bold
      fonts:
        - asset: assets/fonts/sans_bold.ttf
        # - asset: fonts/Schyler-Italic.ttf
        #   style: italic